import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background text-foreground relative selection:bg-primary/20 selection:text-primary overflow-x-hidden`}
      >
        {/* Background Decorators - Enriched Aurora & Pattern Effect */}
        <div className="fixed inset-0 z-0 bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.15),rgba(255,255,255,0))]" />

        {/* Subtle grid pattern for texture */}
        <div className="fixed inset-0 z-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-size-[24px_24px] mask-[radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)] pointer-events-none" />

        {/* Floating colorful orbs */}
        <div className="fixed top-[-10%] left-[-10%] w-[500px] h-[500px] rounded-full bg-emerald-500/15 blur-[120px] pointer-events-none mix-blend-screen z-0 animate-pulse animation-duration-[10s]" />
        <div className="fixed top-[50%] left-[50%] w-[500px] h-[500px] rounded-full bg-blue-500/10 blur-[120px] pointer-events-none mix-blend-screen z-0 animate-pulse animation-duration-[10s] delay-1000" />
        <div className="fixed bottom-[-20%] left-[20%] w-[600px] h-[600px] rounded-full bg-indigo-500/10 blur-[150px] pointer-events-none mix-blend-screen z-0" />
        <div className="fixed top-[20%] right-[-10%] w-[400px] h-[400px] rounded-full bg-rose-500/15 blur-[120px] pointer-events-none mix-blend-screen z-0 animate-pulse animation-duration-[10s] delay-2000" />
        <div className="fixed bottom-[10%] right-[10%] w-[500px] h-[500px] rounded-full bg-blue-500/10 blur-[150px] pointer-events-none mix-blend-screen z-0" />

        <div className="relative z-10 w-full h-full">{children}</div>
      </body>
    </html>
  );
}
